CliMA/CalibrateEDMF.jl

experiments/scm_pycles_pipeline/calibrate.jl
src/helper_funcs.jl

1.) Retry SCM run up to 5x when a simulation fails, to avoid crashing the entire EKP pipeline.
2.) Add a tmp dir to prevent `scm_pycles_pipeline` dir from becoming cluttered.

retry on failed simulations

---

experiments/scm_pycles_pipeline/calibrate.jl
src/helper_funcs.jl

This PR adds more regularization options to the `ReferenceStatistics` struct. In particular,
- It adds the option to specify the retained variance fraction in PCA.
- It adds the option to specify the magnitude of Tikhonov regularization.
- It adds the option to scale the covariance by the dimension of each observed vector.

Add more regularization options to ReferenceStatistics.

---

experiments/les_strats/tc_calibrate.jl
experiments/scm_pycles_pipeline/hpc_parallel/init.jl
experiments/scm_pycles_pipeline/julia_parallel/calibrate.jl
src/ReferenceModels.jl
src/ReferenceStats.jl
src/TurbulenceConvectionUtils.jl
src/helper_funcs.jl
test/ReferenceModels/runtests.jl

Replaces root & suffix attributes with full simulation directories in `ReferenceModel` object + propagates changes throughout codebase. I'm still working out an `InexactError`, but this is my thinking for how to deal with the paths.

specify les, scm relative directories

---

.gitignore

This PR adds an entry for the directory `.vscode` in `.gitignore` to ignore edits to local editor settings.

ignore vscode config

---

experiments/les_strats/config.jl
experiments/les_strats/tc_calibrate.jl
experiments/scm_pycles_pipeline/julia_parallel/calibrate.jl
src/LESUtils.jl
src/ReferenceModels.jl
src/ReferenceStats.jl
src/helper_funcs.jl
test/LESUtils/runtests.jl

This PR makes use of the TC.jl variable alias dictionary housed in `TC.jl/src/name_aliases.jl`.
Instead of checking which variable exists in the netCDF file every time before fetching, we first look up the aliases present in our ReferenceModel data, and we pass that to the rest of the functions, so that lookup is constant in time afterwards, and we don't have to extend support to tuples of strings.

Use TC.jl alias dictionary.

---

experiments/les_strats/config.jl
experiments/les_strats/tc_calibrate.jl
experiments/scm_pycles_pipeline/config.jl
experiments/scm_pycles_pipeline/hpc_parallel/ekp_calibration.sbatch
experiments/scm_pycles_pipeline/hpc_parallel/init.jl
experiments/scm_pycles_pipeline/hpc_parallel/init.sbatch
experiments/scm_pycles_pipeline/hpc_parallel/precondition_prior.jl
experiments/scm_pycles_pipeline/hpc_parallel/single_scm_eval.jl
experiments/scm_pycles_pipeline/hpc_parallel/step_ekp.jl
experiments/scm_pycles_pipeline/hpc_parallel/step_ekp.sbatch
experiments/scm_pycles_pipeline/julia_parallel/calibrate.jl
src/Pipeline.jl
src/ReferenceStats.jl
src/TurbulenceConvectionUtils.jl
test/Pipeline/config.jl
test/Pipeline/runtests.jl

This PR simplifies the pipeline, and adds the ModelEvaluator struct, which houses all the information required to evaluate the SCM forward model.

Simplify pipeline, avoid preconditioning for unscented inversion.

---

experiments/scm_pycles_pipeline/hpc_parallel/step_ekp.jl
src/CalibrateEDMF.jl
src/NetCDFIO.jl
src/Pipeline.jl
test/NetCDFIO/runtests.jl
test/runtests.jl

This PR adds the NetCDFIO module, based on the module of the same name from `TC.jl`. We want to ideally move all diagnostic output to this centralized file, since keeping track of many `jld2` files is more tedious, seems to have a larger memory overhead, and cannot be read from python directly. A step towards #91 .
1. The module defines diagnostic dictionaries associated with different groups (ensemble diagnostics, particle diagnostics, reference and metrics) with some examples (I have added just a few variables so far).
2. The module defines io functions for the different groups, trying to push all the diagnostic definition and writing to the backend.
I have also added a few tests, and the function is now used in the HPC pipeline.

Add NetCDFIO module, output to NetCDF.

---

experiments/les_strats/tc_calibrate.jl
experiments/scm_pycles_pipeline/hpc_parallel/step_ekp.jl
experiments/scm_pycles_pipeline/julia_parallel/calibrate.jl
src/NetCDFIO.jl
src/Pipeline.jl
src/helper_funcs.jl
test/NetCDFIO/runtests.jl
test/runtests.jl

This PR refactors the diagnostics dictionaries, detaching the fields from the rest of the definition, so that the dictionaries can be called at initialization time when the fields are not known.
It also adds a few NetCDF diagnostics related to model error.

Refactor diagnostic dictionaries, add more NetCDF diagnostics.

---

experiments/scm_pycles_pipeline/hpc_parallel/ekp_calibration.sbatch
experiments/scm_pycles_pipeline/hpc_parallel/init.jl
experiments/scm_pycles_pipeline/hpc_parallel/step_ekp.jl
experiments/scm_pycles_pipeline/hpc_parallel/step_ekp.sbatch
src/NetCDFIO.jl
src/Pipeline.jl
src/ReferenceStats.jl
src/helper_funcs.jl
test/NetCDFIO/runtests.jl
test/Pipeline/runtests.jl

This PR:
- Adds more NetCDF diagnostics, ensuring type stability (before, variables were cast to floats).
- Modifies the "relative" Tikhonov regularization mode, now the `tikhonov_noise` has the interpretation of the maximum condition number of the covariance matrix in the inverse problem, which defaults to 10*sqrt(eps(FT)) to ensure stability when the "relative" mode is chosen.
- Writes the config file to the output file, so that the calibration process is fully determined from the contents of the output directory. It also adds a random number to the output directory to allow for multiple calibration processes to be run at the same time without enlarging further the name of the output file.

Add more diagnostics, modify relative covariance conditioning, ensure type in NetCDF output.

---

experiments/les_strats/config.jl
experiments/scm_pycles_pipeline/config.jl
src/NetCDFIO.jl
src/Pipeline.jl
src/ReferenceModels.jl
src/ReferenceStats.jl
test/ReferenceModels/runtests.jl

This PR modifies the time shift function so that the time intervals are not fixed for `y` and `Σ`, but actually given by the requested time interval in the config file (which is written with respect to the `t=0` of the SCM).
In addition,
- I have modified the `Σ` time interval for the `LesDrivenScm` config file to encompass the whole LES time series. Note that the rank of the covariance matrix is at most the number of samples in time, and since the LES output for the LesDrivenScm case is so coarse, otherwise you end up with just a few points! Taking the whole time series ensures that you get 828 sample points.
- I have added a diagnostic for the PCA projection matrix.
- I have fixed a bug in the Pipeline, although I think it was only wrong in a corner case.

Make time shift consistent with requested times in LesDrivenSCM, add pca diag.

---

src/DistributionUtils.jl
src/Pipeline.jl
src/TurbulenceConvectionUtils.jl

In preparation for function learning we'll need to seamlessly deal with parameter names that correspond to vectors. This is handled here by treating each vector component as a unique parameter in EKP.

Handle parameter names corresponding to vectors

---

README.md

- Update readme to reflect that we now use published versions of TC.jl and EKP.jl, while retaining dev mode instructions.
- Add codecov tracking.

Update Readme, add codecov tracking.

---

experiments/les_strats/config.jl
experiments/scm_pycles_pipeline/config.jl
experiments/scm_pycles_pipeline/hpc_parallel/step_ekp.jl
src/NetCDFIO.jl
src/Pipeline.jl
src/ReferenceModels.jl
test/Pipeline/config.jl

This PR adds the option to minibatch ReferenceModels during the calibration process. Batching is controlled through the ReferenceModelBatch struct, which stores the global vector of ReferenceModels to evaluate, and a vector of pointers to ReferenceModels that dictates the evaluation order for every epoch.
The current implementation is operational for the hpc pipeline for now, and for Ensemble Kalman Inversion. In addition, the netcdf diagnostics file for minibatched simulations does not include model evaluation output, only the errors.

Add minibatching option, ReferenceModelBatch struct.

---

src/Pipeline.jl
src/ReferenceStats.jl
src/TurbulenceConvectionUtils.jl
src/helper_funcs.jl
test/NetCDFIO/runtests.jl
test/Pipeline/config.jl
test/Pipeline/runtests.jl
test/ReferenceModels/runtests.jl
test/ReferenceStats/runtests.jl

Explicitly fetch/generate namelist from TC, then modify the time step in the namelist so that reference SCM simulation is only run 1 step forward. This generates the necessary z-levels, and cell/face variable info for calibration.
Depends on https://github.com/CliMA/TurbulenceConvection.jl/pull/525.
TODO: Check that TC doesn't write namelist to output directory, otherwise all calibration studies will have incorrect `t_max`.

refactor: run short simulation for reference SCM

---

experiments/scm_pycles_pipeline/config.jl
experiments/scm_pycles_pipeline/hpc_parallel/precondition_prior.jl
experiments/scm_pycles_pipeline/hpc_parallel/single_scm_eval.jl
src/NetCDFIO.jl
src/Pipeline.jl
src/TurbulenceConvectionUtils.jl
src/helper_funcs.jl
test/NetCDFIO/runtests.jl
test/Pipeline/config.jl
test/Pipeline/runtests.jl
test/ReferenceModels/runtests.jl
test/ReferenceStats/runtests.jl

This PR:
- Adds defaults to many config values, such that if the key is not found in the config dict, the default is used. This is performed with the function `get_entry`, which wraps around Julia's native `get` to add a warning message if the default is accessed.
- Reduces the time and space resolution of simulations in the tests so that they run faster.
- Increases code coverage to include the `ReferenceModelBatch` construct.

Add config defaults to pipeline

---

test/Pipeline/runtests.jl

This PR extends the tests to cover the `ek_update` function and helper functions, increasing total coverage by 14.23%.

Extend Pipeline test coverage to include ek_update.

---

experiments/les_strats/config.jl
experiments/scm_pycles_pipeline/config.jl
experiments/scm_pycles_pipeline/hpc_parallel/init.jl
experiments/scm_pycles_pipeline/hpc_parallel/precondition_prior.jl
experiments/scm_pycles_pipeline/hpc_parallel/single_scm_eval.jl
experiments/scm_pycles_pipeline/hpc_parallel/single_scm_eval.sbatch
experiments/scm_pycles_pipeline/hpc_parallel/step_ekp.jl
experiments/scm_pycles_pipeline/julia_parallel/calibrate.jl
experiments/scm_pycles_pipeline/julia_parallel/calibrate_script
src/LESUtils.jl
src/NetCDFIO.jl
src/Pipeline.jl
src/ReferenceModels.jl
src/ReferenceStats.jl
src/helper_funcs.jl
test/NetCDFIO/runtests.jl
test/Pipeline/runtests.jl
test/ReferenceStats/runtests.jl

This PR adds validation capabilities to the calibration pipeline. Validation is activated if there exists a `config["validation"]` dictionary that points to a valid reference configuration. In that case, the selected reference configuration is used for validation throughout the calibration process.
The validation forward model evaluations are run as independent `single_scm_run.jl` evaluations. They are called in parallel using hpc resources when calling `single_scm_rub.sbatch`, so the validation evaluations are embarrassingly parallel with respect to calibration. In the pmap pipeline, the training/validation pmap calls are serialized.
In addition, this PR:
- Unifies even further the HPC and pmap pipelines. Now most functionality is shared between them.
- Fixes a bug in the cfSite getter, …

Add validation capabilities to pipeline.

---

src/NetCDFIO.jl
src/TurbulenceConvectionUtils.jl

Fixes the order of the diagnostics update. First, we output all forward model evaluation diagnostics for `iter`, and then all parameter state diagnostics for `iter+1`.
In addition, this PR also improves the output message when a TC.jl simulation fails, including the name of the case that failed.

Fix state diagnostics order.

---

experiments/scm_pycles_pipeline/global_parallel/ekp_par_calibration.sbatch
experiments/scm_pycles_pipeline/global_parallel/parallel_scm_eval.jl
experiments/scm_pycles_pipeline/global_parallel/parallel_scm_eval.sbatch
src/TurbulenceConvectionUtils.jl
src/parallel.jl

This PR adds functionality for parallelism across simulations. An example of the setup is included in `scm_pycles_pipeline/global_parallelism`.
Closes #83 .

Add global parallelism functionality.

---

src/Pipeline.jl

This PR provides a friendly error message if the reference config file has inconsistent shape. i.e., the length of the lists provided to various keywords is different from the number of cases to calibrate.
closes #134

fix: validate shape of reference config

---

experiments/les_strats/config.jl
experiments/scm_pycles_pipeline/config.jl
src/Diagnostics.jl
src/NetCDFIO.jl
src/Pipeline.jl
src/ReferenceStats.jl
test/Pipeline/runtests.jl

This PR enables augmentation of the observational vector `y` with the mean of the prior over the parameters theta. This augmentation acts as an L2 regularizer on the loss. The covariance used to modulate the L2 regularization magnitude is taken as:
- The prior covariance if unspecified, and `augmented` is set to true.
- A diagonal matrix with diagonal elements equal to `l2_reg` if `l2_reg` is given, and it is a float.
-`l2_reg` if it is a matrix.

Enable augmentation of output with parameters for l2 regularization

---

ekp_experimental/failsafe_inversion.jl
experiments/les_strats/config.jl
src/Pipeline.jl

Adds a conditional-on-success failure handling method to the Unscented Kalman Inversion.
The handler is applied during the analysis step, by computing the ill-defined means and covariances over the successful particles. In order to preserve the sum of the weighting scheme, the weights at each successful sigma point are scaled up.
Consider a set of sigma points {θ_j}={θ_succ_j} U {θ_fail_j}, from which we have to estimate E[G], Cov(G, G) and Cov(G, θ) for the UI update rules. These would generally be computed through the quadrature rules of UKI (possibly modified following Huang et al 2021).
In the case of failed particles, i.e. {θ_fail_j} is not the empty set, for the mean of the forward model eval we do:
- E[G] ≈ ∑_succ [(∑W_j) / (∑_succ W_j) * W_j * G(θ_succ_j)] if the center particle …

Add failsafe UKI update.

---

src/Pipeline.jl
src/ReferenceModels.jl
src/ReferenceStats.jl
src/TurbulenceConvectionUtils.jl
src/parallel.jl
test/Pipeline/runtests.jl
test/ReferenceModels/runtests.jl

Adds the option to calibrate at a non-native resolution (i.e., a resolution different than the reference SCM resolution).
This is done by storing a given number of observations, `n_obs`, in each ReferenceModel object. If not nothing, then calibration is done at `n_obs` spatial locations per field, uniformly spaced between the first and last points of the reference SCM vertical domain. This decouples the vertical spacing between the training and validation set as well.

Enable learning at non-native vertical resolution.

---

ekp_experimental/failsafe_inversion.jl
src/Diagnostics.jl
src/NetCDFIO.jl
src/Pipeline.jl

Adds:
- Prior diagnostics in both constrained and unconstrained space.
- NaN-safe diagnostics of the MSE ensemble variance both for ensemble and unscented (i.e., quadrature) methods.
In order to add these diagnostics:
- Adds `construct_mean` and `construct_cov` UKI methods that take vectors, not only matrices. These are useful for diagnostic purposes, and should be ported to the upstream package EKP.jl.

Add prior diagnostics, and failsafe MSE variance diagnostics.

---

src/NetCDFIO.jl
src/Pipeline.jl
test/NetCDFIO/runtests.jl

I am changing the input vars for NetCDFIO_Diags so that in my future PR with grid search I can all 'NetCDFIO_Diags' without 'ekp' as input

change function inputs

---

src/DistributionUtils.jl
src/Pipeline.jl
test/DistributionUtils/runtests.jl
test/Pipeline/runtests.jl

Allow for vector of prior means + make data structures for prior means + constraints consistent. This will require prior means to be specified with a `Vector{Float64}` in the config file in the same manner as constraints. (ie `"surface_area" => [0.1]`)

handle vector of prior mean, constraints consistently

---

src/Diagnostics.jl
src/NetCDFIO.jl
src/Pipeline.jl
src/ReferenceModels.jl
src/TurbulenceConvectionUtils.jl
src/parallel.jl
test/Pipeline/runtests.jl
test/ReferenceModels/runtests.jl

- Adds information about ReferenceModels used per iteration when using batches of data.
- Stores forward model evaluations in Diagnostics even when using batching. These forward model evaluations correspond to the output of ReferenceModels indexed by `batch_indices`.
- Writes to file the diagonal of the full covariance matrix, needed to de-normalize profiles and recover the uncertainty used in the inverse problem. This avoids the need to store the full covariance matrix, which can be extremely large.

Add batch-specific diagnostics.

---

src/TurbulenceConvectionUtils.jl

Prior behavior:
- Calibration process fails during the preconditioning step if preconditioning does not result in a successful ensemble after `max_counter` samples of the prior.
New behavior:
- Preconditioner is run until `max_counter` is encountered or preconditioning is successful. Control is then returned without throwing an error, only logging an error message if `max_counter` is reached.

Return control even if preconditioner fails.

---

.buildkite/pipeline.yml
test/runtests.jl

This PR moves all of our unit tests to buildkite to parallelize them. This technically limits our test coverage on other operating systems (and will effectively kill our code coverage reports), but it will make CI quite faster.
lol, and MacOS agents are taking just as long to test `@test 1 == 1` on GHA, so maybe we can next remove our bors check on GHA CI (we can still run it). Actually, maybe in a follow-up PR I'll add the GHA CI tests back in but just not depend on it with bors.

Perform unit tests on buildkite

---

bors.toml
test/runtests.jl

This PR reverts a part of #195. This will fix our coverage, which dropped. Now, we'll still run GHA CI, but bors will only depend on codecov, in order to keep CI time down.
cc @ilopezgp

Add GHA tests back in, make bors not depend on GHA

---

experiments/SCT1_benchmark/config.jl
experiments/SCT1_benchmark/global_parallel/parallel_scm_eval.jl
experiments/SCT1_benchmark/global_parallel/precondition_prior.jl
experiments/SCT1_benchmark/global_parallel/step_ekp.jl
experiments/les_strats/tc_calibrate.jl
experiments/scm_pycles_pipeline/global_parallel/parallel_scm_eval.jl
experiments/scm_pycles_pipeline/hpc_parallel/precondition_prior.jl
experiments/scm_pycles_pipeline/hpc_parallel/single_scm_eval.jl
experiments/scm_pycles_pipeline/hpc_parallel/step_ekp.jl
experiments/scm_pycles_pipeline/julia_parallel/calibrate.jl
src/CalibrateEDMF.jl
src/Diagnostics.jl
src/HelperFuncs.jl
src/LESUtils.jl
src/NetCDFIO.jl
src/Pipeline.jl
src/ReferenceModels.jl
src/ReferenceStats.jl
src/TurbulenceConvectionUtils.jl
src/parallel.jl
test/Pipeline/config.jl
test/Pipeline/runtests.jl
test/ReferenceModels/runtests.jl
test/helper_funcs/runtests.jl

This PR makes `helper_funcs.jl` a module inside CalibrateEDMF.jl and utilizes the module in various places. This should help compiling fewer versions of the same code.
I think what I've done should work, but we should probably still try testing other parallel schemes with this PR since this changes how code is loaded.
We should do this (and possibly merge?) with `src/parallel.jl`.

Compile less code

---

src/HelperFuncs.jl

It's better to use `haskey` over `try-catch` when we can. This PR changes to use `haskey`.

Remove a try-catch

---

experiments/scm_pycles_pipeline/Artifacts.toml
experiments/scm_pycles_pipeline/config.jl
experiments/scm_pycles_pipeline/julia_parallel/calibrate.jl
src/HelperFuncs.jl

I've uploaded the data from `"/groups/esm/zhaoyi/pycles_clima/Output.Bomex.aug09"` to Caltech Box, and it's now lazily downloaded using Artifacts.
This PR allows us to run locally:
```julia
julia --project
using Distributed # maybe needed?
include("experiments/scm_pycles_pipeline/julia_parallel/calibrate.jl")
```
cc @yairchn 
I'm hoping that this can also be run in a distributed fashion using
```julia
julia -p 4 --project
using Revise; include(joinpath("experiments", "scm_pycles_pipeline", "julia_parallel", "calibrate.jl"))
```
(hopefully fixing #201).

Use artifacts (enable local run) improve paths

---

.buildkite/pipeline.yml

This PR adds a julia parallel job to buildkite that runs with 10 processors, just so that a multi-processor job is tested.
Note that `julia -p 10` specifies 10 workers, and `slurm_ntasks: 11` specifies the total number of tasks.

Add a multi-processor job to buildkite

---

src/HelperFuncs.jl

Logs whether the default was used in `get_entry` at the info level. From recent experience using a warning has been distracting users while debugging. This warning was typically ok to ignore since some configurations will resort to defaults in operational use.

Log use of get_entry defaults to info.

---

src/ReferenceStats.jl
test/ReferenceStats/runtests.jl
test/TurbulenceConvectionUtils/runtests.jl

Moves PCA checks to unit tests to reduce computational cost of pipeline, adds more tests verifying that PCA is exactly defined as intended.
Also modularizes the PCA function.

Add more PCA unit tests.

---

src/TurbulenceConvectionUtils.jl

I don't think users need to see the timings for every TC run. This should help reduce the noise in our log for the multi-node runs.

Reduce log output with time_run = false

---

src/TurbulenceConvectionUtils.jl
src/parallel.jl

This PR combines the `@info` statements from
```julia
[ Info: Length of g_scm (full): 180
[ Info: Length of g_scm (pca) : 13
```
to
```julia
[ Info: Length of g_scm (full, pca): (180, 13)
```
to help compactify the logging a bit (multi-processor runs still log quite a bit of info).

Make log a bit more compact

---

integration_tests/julia_parallel_calibrate.jl

This PR
- prints some of the metrics in the integration tests
- Adjusts the plot margins so that the label is (hopefully) visible when increasing the number of iterations
- Adds `ENV["GKSwstype"] = "nul"` (see related issue)

Print mse vectors, pad left margin plots

---

src/TurbulenceConvectionUtils.jl

We should probably use at least log level `Warn` when running TC so that we can see why it fails. Sorry I silenced everything with the NullLogger. cc @zongyi-li

Use warn log level for TC runs

---

src/ReferenceModels.jl

#231 broke getting files that don't match a specific pattern, this PR fixes this issue. Hopefully we can move the call `get_stats_path` call into the `ReferenceModel` constructors and have the getters return cached strings. I tried doing this in #236, but I'm running into snags and I don't want users to stay stuck.

Make nc file getter functions match more flexibly

---

experiments/SCT1_benchmark/config.jl
experiments/SCT1_benchmark/global_parallel/precondition_prior.jl
experiments/SCT1_benchmark/global_parallel/restart.jl
experiments/SCT1_benchmark/global_parallel/restart.sbatch
experiments/SCT1_benchmark/global_parallel/restart_ekp_par_calibration.sbatch
experiments/SCT1_benchmark/global_parallel/step_ekp.jl
src/Pipeline.jl
test/Pipeline/runtests.jl

- Adds Pipeline functions that allow restarting a calibration process, `restart_calibration` and `restart_validation`.
- Adds a global_parallel restart pipeline. To run the pipeline, do
```
sbatch restart_ekp_par_calibration.sbatch <results_dir_of_process_to_be_restarted>
```
This commands restarts the calibration process stored in `<results_dir_of_process_to_be_restarted>`, using the configuration stored in said directory.
The restarted simulation will continue to a grand total of `process_config["N_iter"]`, starting from the number of calibration steps that already occurred. This means that if the process had run for 50 iterations and we set process_config["N_iter"]=75, the restarted calibration will run for an additional 25 iterations. So, in order to continue a calibration that had …

Add restart option for global_parallel

---

src/DistributionUtils.jl
src/ReferenceStats.jl
test/Pipeline/runtests.jl

- Allows defining the level of l2 regularization through a dictionary from parameter names to values of l2_reg. This is consistent to how we define priors, making anisotropic l2 regularization more user friendly.

Allow definition of l2_reg through a dictionary.

---

.buildkite/pipeline.yml
integration_tests/Bomex_integration_test_config.jl
integration_tests/SCT1_integration_test_config.jl
integration_tests/julia_parallel_test.jl

- Adds a Julia parallel test for the ReferenceModels used in the SCT1 benchmark.
- The launch script is unified for this and the bomex integration test.
- The config files are now located in the integration tests to decouple them from the experiments.
- Both tests together test most of the diagnostics that we want to have with `calibrate_io`.
- Time to solution will be improved once we can set `calibrate_io` to true. Right now buildkite time is dominated by the SCT1 integration test, which takes <40 min for 2 iterations of UKI.

Add an integration test for the SCT1 benchmark.

---

.buildkite/pipeline.yml
integration_tests/Bomex_integration_test_config.jl
integration_tests/continue_julia_parallel_test.jl

- Adds an integration test for a restart calibration that is run for an additional 5 steps.
- Speeds up the Bomex integration test by setting `calibrate_io` to true. This works for the outputs we are using in the Bomex-config, but not others (e.g, entropy).

Add integration test for calibration restart, speed up Bomex.

---

experiments/SCT1_benchmark/config.jl
experiments/les_strats/config.jl
experiments/scm_pycles_pipeline/config.jl
integration_tests/Bomex_integration_test_config.jl
integration_tests/SCT1_integration_test_config.jl
src/Pipeline.jl
src/ReferenceStats.jl
test/Pipeline/runtests.jl
test/ReferenceStats/runtests.jl

- Augments system for nonzero regularized dimensions only. The previous implementation augmented the system with all dimensions and returned variances of 1/eps(FT) for dimensions with 0 regularization. This change should greatly improve stability for partial regularization.
- Enforces more explicitly that the passed regularization dictionary is complete. Allow passing partial dicts is a bit more involved, so we will avoid this for now. The way we choose unregularized dimensions is by setting them to 0.

Augment system for nonzero regularizations only, improve error messages.

---

experiments/scm_pycles_pipeline/README.md
experiments/scm_pycles_pipeline/julia_parallel/calibrate_script

This PR makes you specify which config file to use for a calibration run explicitly when using the Julia parallel (pmap) pipeline. e.g.:
```sbatch calibrate_script ../config.jl ```
instead of 
```sbatch calibrate_script ```
which would assume the config file was `../config.jl`. As such, other config file paths can be used.

explicity specify config path for julia_parallel runs

---

.buildkite/pipeline.yml
experiments/SCT1_benchmark/README.md
experiments/SCT1_benchmark/global_parallel/create_tc_so.jl
experiments/SCT1_benchmark/global_parallel/ekp_par_calibration.sbatch
experiments/SCT1_benchmark/global_parallel/init.sbatch
experiments/SCT1_benchmark/global_parallel/parallel_scm_eval.sbatch
experiments/SCT1_benchmark/global_parallel/precondition_prior.sbatch
experiments/SCT1_benchmark/global_parallel/restart.sbatch
experiments/SCT1_benchmark/global_parallel/restart_ekp_par_calibration.sbatch
experiments/SCT1_benchmark/global_parallel/step_ekp.sbatch
experiments/SCT1_benchmark/global_parallel/sysimage.sbatch
integration_tests/Bomex_sparseinversion_test_config.jl
integration_tests/Manifest.toml
integration_tests/continue_julia_parallel_test.jl
integration_tests/julia_parallel_test.jl

Adds a system image precompilation to the global_parallel calibration pipeline. The cpu_target of precompiled code seems to be somewhat randomly unstable, so we implement a fallback mechanism such that if the system image is detected as _not compatible with the target_, we can continue calibration without the system image for that particular process.
We also enforce the cpu_target of Julia calls within the pipeline to `skylake-avx512`, the microarchitecture in the Caltech central cluster.

Add system image precompilation to global_parallel pipeline

---

.buildkite/pipeline.yml
integration_tests/Het_batch_unscented_test_config.jl
integration_tests/Manifest.toml
integration_tests/julia_parallel_test.jl
src/Diagnostics.jl
src/NetCDFIO.jl

This PR enables training with heterogeneous (i.e., different size) minibatches, fixing #285.
This was previously not possible because we assumed homogeneity in the dimension of `g_full` for any batch, which is only true when training on ReferenceModels with the same number of fields and same number of vertical levels. We fix this by:
- Changing the allocated dimension of `g_full` and `g_full_val` in the diagnostics netCDF to the maximum possible dimension of the problem, regardless of the batching strategy. These arrays are then filled starting from the leading element, so when batching there is a trailing set of zeroes that are not filled.
- The same approach is taken for the number of fields per configuration. This dimension of the netCDF array is now taken to be the maximum number of …

Fix and test issue #285

---

docs/src/API/ReferenceStats.md
integration_tests/Manifest.toml
src/ReferenceModels.jl
src/ReferenceStats.jl

Documenter does not show `docstrings` of inner or outer constructors explicitly. In order to show constructors in docs, we move here the constructor documentation to the `docstring` of the struct.

Move constructors docs to struct docstring for Documenter 

---

.buildkite/pipeline.yml
docs/src/API/KalmanProcessUtils.md
integration_tests/Bomex_inversion_test_config.jl
integration_tests/Manifest.toml
src/KalmanProcessUtils.jl
src/Pipeline.jl
test/KalmanProcessUtils/runtests.jl
test/runtests.jl

Adds learning rate schedulers `PiecewiseConstantDecay` and `PiecewiseConstantGrowth` to the calibration pipeline.
#314

Add learning rate schedulers

---

docs/src/API/Diagnostics.md
integration_tests/Manifest.toml
src/Diagnostics.jl
src/KalmanProcessUtils.jl

Adds more diagnostics about the training loss in latent space (as opposed to the full MSE). These are diagnostics of the loss actually minimized by the ensemble Kalman processes.
The newly added loss diagnostics also filter for `NaN`s, which is not the case when using the off-the-shelf `loss_mean_g`.

Add loss diags

---

.dev/Project.toml
docs/src/API/ReferenceModels.md
docs/src/API/TurbulenceConvectionUtils.md
experiments/SCT1_benchmark/config.jl
experiments/SCT2_benchmark/config.jl
integration_tests/Bomex_inversion_test_config.jl
integration_tests/Bomex_sparseinversion_test_config.jl
integration_tests/Manifest.toml
integration_tests/SCT1_integration_test_config.jl
src/Diagnostics.jl
src/HelperFuncs.jl
src/KalmanProcessUtils.jl
src/NetCDFIO.jl
src/Pipeline.jl
src/ReferenceModels.jl
src/ReferenceStats.jl
src/TurbulenceConvectionUtils.jl
src/parallel.jl
test/NetCDFIO/runtests.jl
test/Pipeline/config.jl
test/Pipeline/runtests.jl
test/ReferenceModels/runtests.jl
test/ReferenceStats/runtests.jl
test/TurbulenceConvectionUtils/runtests.jl

Constructs the vector of observations and reference namelist at ReferenceModel construction time and stores them within the struct. This approach has a number of advantages:
- Reduces number of calls to the infamous `get_stats_path`,
- Stores observational grid points within ReferenceModel, which enables writing them to the Diagnostics. Right now it was only possible to reconstruct them implicitly based on constant `dz` assumptions, which we want to move away from,
- Enables passing non-default grid namelist arguments separately to each ReferenceModel. This allows greater flexibility than the current approach, in which we either calibrated to the default resolution or to a common resolution for all cases.
- Removes the need to use `run_reference_SCM`! We retain the function to be able to …

Store z_obs vector and reference namelist in ReferenceModel.

---

src/Pipeline.jl

The current code would fail for 
https://github.com/CliMA/CalibrateEDMF.jl/blob/369f479e9a723b446dfd4c77a3b58d4e1376cfa5/src/Pipeline.jl#L452-L454
since `l2_reg` would be undefined, unless `augmented` is `true`, so that the following preceding code was is called
https://github.com/CliMA/CalibrateEDMF.jl/blob/369f479e9a723b446dfd4c77a3b58d4e1376cfa5/src/Pipeline.jl#L434-L440
This PR moves the definition of `l2_reg` out of that conditional block.

fix: l2_reg scope

---

experiments/SCT1_benchmark/global_parallel/restart.jl
experiments/SCT2_benchmark/global_parallel/restart.jl

* do glob with prefix
* fetch most recent ekobj_iter_XX.jld file more robustly
1. **glob bug**
if `outdir_path` is an absolute path, 
```julia
ekobjs = glob(joinpath(outdir_path, "ekobj_iter_*.jld2"))
```
will fail. instead, `outdir_path` should be specified as the prefix for the search query (`"ekobj_iter_*.jld2"`).
2. **ekobj_iter_XX.jld2 bug**
If `ekobjs` is an absolute path that contains `_` and/or `.` in the pathname, 
```julia
iters = [parse(Int64, split(split(split(ekobj, "/")[2], "_")[3], ".")[1]) for ekobj in ekobjs]
```
may fail. Instead, match a regex query to get the relevant integers.

fix: SCT1 and SCT2 restart calibration bug

---

integration_tests/Manifest.toml

fix integration tests CEDMF dependency to `dev ..`

---

.gitignore
docs/src/API/HelperFuncs.md
experiments/grid_search/grid_search.jl
integration_tests/Manifest.toml
src/Diagnostics.jl
src/DistributionUtils.jl
src/HelperFuncs.jl
src/Pipeline.jl
src/TurbulenceConvectionUtils.jl
src/parallel.jl
test/HelperFuncs/runtests.jl
test/NetCDFIO/runtests.jl
test/Pipeline/runtests.jl
test/TurbulenceConvectionUtils/runtests.jl
tools/TCRunner.jl

This PR is intended to allow for simple functional dependencies between parameters to be calibrated. The primary use cases are the following:
1. Given a parameter vector, this PR allows you to calibrate a subset of its components, keeping the other components to their default values.
2. Define an equality relation between two parameters, either scalar parameters or components of vector parameters.
In practice, to handle this, the struct `ParameterMap` is introduced:
https://github.com/CliMA/CalibrateEDMF.jl/blob/fa654dd8911895bbe4b08559b635f420270c4261/src/HelperFuncs.jl#L101-L103
The struct contains `mapping`, which is a dictionary that defines how to specify values of parameters that aren't explicitly a part of the calibration process. The dictionary keys are these parameters, while the …

parameter masking

---

integration_tests/test_create_tc_so.jl

reduces time to build system image from ~30-40 mins to < 15 mins

simplify system-image test by not running a precompile execution file

---

docs/src/API/TurbulenceConvectionUtils.md
experiments/SCT1_benchmark/NN_closure/buoy_vel_no_reg/e100/config.jl
experiments/SCT1_benchmark/NN_closure/buoy_vel_no_reg/e50/config.jl
experiments/SCT1_benchmark/NN_closure/buoy_vel_reg_0.1/config.jl
experiments/SCT1_benchmark/NN_closure/inv_z_l2_reg_0.1/config.jl
experiments/SCT1_benchmark/NN_closure/inv_z_no_reg/e100/config.jl
experiments/SCT1_benchmark/NN_closure/inv_z_no_reg/e50/config.jl
experiments/SCT1_benchmark/NN_closure/none_no_reg/e100/config.jl
experiments/SCT1_benchmark/NN_closure/none_no_reg/e50/config.jl
experiments/SCT1_benchmark/NN_closure/none_reg_0.1/config.jl
experiments/SCT1_benchmark/global_parallel/parallel_scm_eval.jl
experiments/SCT1_benchmark/global_parallel/precondition_prior.jl
experiments/SCT1_benchmark/moisture_deficit_closure/config.jl
experiments/SCT2_benchmark/NN_closure/inv_z_no_NN_reg/config.jl
experiments/SCT2_benchmark/global_parallel/parallel_scm_eval.jl
experiments/SCT2_benchmark/global_parallel/precondition_prior.jl
experiments/les_strats/config.jl
experiments/les_strats/global_parallel/parallel_scm_eval.jl
experiments/les_strats/global_parallel/precondition_prior.jl
experiments/scm_pycles_pipeline/hpc_parallel/precondition_prior.jl
experiments/scm_pycles_pipeline/hpc_parallel/single_scm_eval.jl
integration_tests/continue_julia_parallel_test.jl
src/HelperFuncs.jl
src/Pipeline.jl
src/TurbulenceConvectionUtils.jl

This pair aims to simplify how naming of `versions` is done during calibration.
A `version` is currently a random 5-digit integer that is associated with an ensemble member in an EKP iteration.
For example, before every iteration, there is be a bunch of `scm_initializer_<version>.jld2` files in the results directory which contains the necessary information to run the simulations associated with each ensemble member.
This PR proposes that `version` is generated deterministically, and is on the form `ix_ey` where `x` is the current iteration index and `y` is the current ensemble index.
The PR serves two purposes, first, it simplifies the logic of #180, and second, it makes it potentially easier to debug calibration runs since you can easily see what each `jld2` file corresponds to.

refactor: simplify versions logic

---

integration_tests/Manifest.toml
src/HelperFuncs.jl
src/Pipeline.jl
test/Pipeline/config.jl
test/ReferenceModels/runtests.jl

There was a bug in the code, which caused the `get_ref_models_kwargs` function to ignore the namelist_args passed to ReferenceModels. This PR fixes that bug, and allows passing different namelist_args for each ReferenceModel.

Fix namelist_args handling during ReferenceModel construction

---

docs/src/API/ReferenceModels.md
driver/hpc_parallel/precondition_prior.jl
experiments/grid_search/grid_search.jl
experiments/grid_search/loss_map.jl
integration_tests/Manifest.toml
src/NetCDFIO.jl
src/Pipeline.jl
src/ReferenceModels.jl
src/TurbulenceConvectionUtils.jl
src/parallel.jl
test/Pipeline/runtests.jl
test/ReferenceModels/runtests.jl
test/TurbulenceConvectionUtils/runtests.jl
tools/TCRunner.jl

Fix specification of both case-specific `namelist_args` and global (i.e. from `config["scm"]`) `namelist_args`.
Case-specific args has precedence over global args, which has precedence over default TC.jl args.
Generalizes a similar issue that was addressed in PR #394.
Closes #393.

fix: unify case-specific and global namelist args

---

src/ReferenceStats.jl
test/ReferenceStats/runtests.jl

This PR allows using the relative covariance Tikhonov regularization, by using eigmax(), instead of the maximum of the covariance matrix.

Allow relative Tikhonov for non_PCA reference_stats

---

driver/global_parallel/parallel_scm_eval.jl
experiments/SCT1_benchmark/global_parallel/parallel_scm_eval.jl
experiments/SCT2_benchmark/global_parallel/parallel_scm_eval.jl
experiments/les_strats/global_parallel/parallel_scm_eval.jl

This PR further unifies code shared among different experiments. In this case, we unify most of the driver code for the `parallel_scm_eval.jl` call from any global_parallel driver of an experiment.

Unify driver code for parallel_scm_eval

---

src/ReferenceStats.jl

This PR converts P_pca to an AbstractMatrix in the corner case that PCA is not actually used. Using UniformScaling precluded proper IO with the netCDF diagnostics.

Convert P_pca to AbstractMatrix when not using PCA.

---

docs/src/API/HelperFuncs.md
experiments/grid_search/grid_search.jl
integration_tests/Manifest.toml
integration_tests/grid_search_integration_test_config.jl
integration_tests/grid_search_test.jl
src/HelperFuncs.jl
src/ReferenceModels.jl
src/TurbulenceConvectionUtils.jl
test/HelperFuncs/runtests.jl
test/TurbulenceConvectionUtils/runtests.jl
tools/TCRunner.jl

Extend #400 by fixing `namelist_args` specification for `TCRunner` and `grid_search` setups.
Add method to update a `namelist` given set of `namelist_args`. With this, `namelist_args` is no longer a keyword argument to `run_SCM_handler`. Instead, any modifications to the `namelist` should be made prior to calling that function. Furthermore, since modifications to the `namelist` is disallowed, it made more sense to make the `namelist` a mandatory method argument, rather than an optional one.
In a future PR, we could optionally also remove `case_name` from the argument list of `run_SCM_handler` since that information is already contained in the `namelist` itself, but that isn't really too important.
Closes #407.

fix `namelist_args` specification for `TCRunner` and `grid_search`

---

src/AbstractTypes.jl
src/CalibrateEDMF.jl
src/Pipeline.jl
src/ReferenceStats.jl
test/ReferenceStats/runtests.jl

This PR adds the possibility to include a structural model error component to the error covariance matrix, with the following characteristics:
- For now, the structural error is taken to be constant per variable and reference model, so one can specify different structural errors for each spatial field of each reference model.
- The additive structural error is specified as a fraction of the pooled variance per variable. For instance, specifying a model error of 0.1 for `u_mean` of a reference model equates to adding to each component a noise with variance of 10% of the pooled variance.
-  The additive structural error is uncorrelated with the time covariance, so all its dimensions remain after performing PCA. This is a useful property because it allows to perform PCA on most variables, …

Add `model_error` option to ReferenceStats constructor

---

integration_tests/Manifest.toml
src/AbstractTypes.jl
src/HelperFuncs.jl
src/KalmanProcessUtils.jl
src/LESUtils.jl
src/Pipeline.jl
src/ReferenceModels.jl
src/ReferenceStats.jl
src/TurbulenceConvectionUtils.jl

Centralized and expands use of abstract typing for optional arguments. Moves exports to top of each module, tidying convention.

Use abstract typing, move exports up.

---

integration_tests/Manifest.toml
tools/TCRunner.jl

This PR fixes an issue introduced in PR #410, where a vector of namelist_args are passed to each TC runner, instead of dispatching each namelist_args to each TC run.

Fix namelist_args dispatch in TCRunner

---

integration_tests/Manifest.toml
tools/DiagnosticsTools.jl
tools/test_sets/amip4k_sct_config.jl
tools/test_sets/amip_sct_config.jl

Adds another valid method for TC diagnostics, the `last_nn_particle_mean`. This method fetches the parameters from the particle closest to the ensemble mean at the last iteration of the calibration process.

Add Diagnostics at last nn_mean

---

docs/src/API/HelperFuncs.md
integration_tests/SCT1_integration_test_config.jl
src/HelperFuncs.jl
src/parallel.jl
test/HelperFuncs/runtests.jl

- Adds the SGS flux contribution to the PyCLES flux diagnostics for calibration, since the EDMF flux is supposed to represent resolved+unresolved components. This is particularly important near the wall in LES, where the flow is still unresolved even in LES. 
- Adds a descriptive docstring about the differences between certain variables in TC.jl and PyCLES. This docstring also renders in the API section of the CalibrateEDMF documentation for readability.
- Removes a duplicate function in `src/parallel.jl` to improve code robustness.

Add sgs flux contribution to LES fluxes. Simplify parallel.

---

integration_tests/Manifest.toml

I want to update to TurbulenceConvection.jl from `v0.34.1` to `v0.34.3` so I ran the `up_deps` script

update deps for TCv0.34.3

---

experiments/SCT3_benchmark/config_no_phys.jl
experiments/SCT3_benchmark/global_parallel/create_tc_so.jl
experiments/SCT3_benchmark/global_parallel/ekp_par_calibration.sbatch
experiments/SCT3_benchmark/global_parallel/init.jl
experiments/SCT3_benchmark/global_parallel/init.sbatch
experiments/SCT3_benchmark/global_parallel/parallel_scm_eval.jl
experiments/SCT3_benchmark/global_parallel/parallel_scm_eval.sbatch
experiments/SCT3_benchmark/global_parallel/precondition_prior.jl
experiments/SCT3_benchmark/global_parallel/precondition_prior.sbatch
experiments/SCT3_benchmark/global_parallel/restart.jl
experiments/SCT3_benchmark/global_parallel/restart.sbatch
experiments/SCT3_benchmark/global_parallel/restart_ekp_par_calibration.sbatch
experiments/SCT3_benchmark/global_parallel/step_ekp.jl
experiments/SCT3_benchmark/global_parallel/step_ekp.sbatch
experiments/SCT3_benchmark/global_parallel/sysimage.sbatch
integration_tests/Het_batch_unscented_test_config.jl
integration_tests/Manifest.toml
run_tests.sbatch
src/LESUtils.jl

- Adds the CNRM-CM5 cases to the allowable TC cases through TC functions, unifies LES libraries with TC codebase.
- Adds a new benchmark, SCT3, with 135 training sites from the AMIP archive (HadGEM2-A + CNRM-CM5), and 15 AMIP4K validation sites from the HadGEM2-A model.
- The SCT3 benchmark should at least contain a config file to calibrate exclusively the data-driven entrainment closure, used as an additive term to the MD closure.
- No regularization used.
- Localization used.
- All physical parameters trained a priori and set to the trained values as defaults through `namelist_args`.
Closes #436

Add CNRM-CM5 cases, add SCT3 benchmark

---

driver/create_tc_so.jl
src/ReferenceModels.jl
test/ReferenceModels/runtests.jl

Fixes some issues regarding the use of perfect model experiments with LES_driven_SCM configs. In particular, the time_shift function assumed that the time coordinate was identical for the observations and the data used to generate the noise, which need not be the case if we take the mean from an `SCM()` and the noise from `LES()`.

Fix mixed LES/SCM ReferenceModels for LES_driven_SCM.

---

experiments/SCT3_benchmark/config_no_phys.jl
experiments/SCT3_benchmark/global_parallel/init.sbatch
integration_tests/Manifest.toml

Update SCT3 to account for new LES library included in TC `v1.2.0`. Specifies 200 LES cases instead of the full 203 to allow for more batch size options.

Update SCT3 to account for new LES cases

---

integration_tests/Manifest.toml
src/DistributionUtils.jl
src/HelperFuncs.jl
src/KalmanProcessUtils.jl
src/Pipeline.jl
test/DistributionUtils/runtests.jl

The behavior of `keys` seems to have changed in julia 1.8, such that calling `collect(keys())` on the prior constraint and mean dicts separately doesn't necessarily result in the same key ordering. This PR ensures `construct_priors` is order-agnostic.

Ensure order-agnostic config prior specification

---

docs/Project.toml
src/Pipeline.jl
src/ReferenceModels.jl
src/ReferenceStats.jl
test/ReferenceModels/runtests.jl

Expose LES_driven_SCM timeshift, so that it can be modified from config files.

Allow reference model time_shift to be specified in config

---

src/HelperFuncs.jl

Use temperature in bottom cell center for applying surface flux correction instead of `surface_temperature`, which isn't available in all LES runs (specifically non-LES-driven cases like Bomex, DYCOMS).

Use temperature in bottom cell center for surface flux recitification 

---

src/HelperFuncs.jl
src/TurbulenceConvectionUtils.jl
test/TurbulenceConvectionUtils/runtests.jl

Ensure `create_parameter_vectors` preserves vector component order. 
`sortperm` was previously sorting strings, not vector indices. This did not affect the quality of calibrations, but made it difficult to interpret vector components after calibration (since they were being reordered).

Ensure create_parameter_vectors preserves vector component order

---

src/TurbulenceConvectionUtils.jl

Export `create_parameter_vectors` from TC utils for external use.

Export create_parameter_vectors from TC utils

---

src/Diagnostics.jl
src/KalmanProcessUtils.jl
src/Pipeline.jl
test/NetCDFIO/runtests.jl
test/Pipeline/config.jl
test/Pipeline/runtests.jl

1. Adds functionality for using native learning rate schedulers from EKP.jl
2. Outputs timestep history to `Diagnostics.nc` output file.
3. Make EKP verbose

add EKP learning rate schedulers 

---

.buildkite/pipeline.yml
experiments/SCT4_benchmark/config_linreg_all_LES.jl
experiments/SCT4_benchmark/config_linreg_precalibration.jl
experiments/SCT4_benchmark/config_nn_all_LES.jl
experiments/SCT4_benchmark/global_parallel/ekp_par_calibration.sbatch
experiments/SCT4_benchmark/global_parallel/init.jl
experiments/SCT4_benchmark/global_parallel/init.sbatch
experiments/SCT4_benchmark/global_parallel/parallel_scm_eval.jl
experiments/SCT4_benchmark/global_parallel/parallel_scm_eval.sbatch
experiments/SCT4_benchmark/global_parallel/precondition_prior.jl
experiments/SCT4_benchmark/global_parallel/precondition_prior.sbatch
experiments/SCT4_benchmark/global_parallel/restart.jl
experiments/SCT4_benchmark/global_parallel/restart.sbatch
experiments/SCT4_benchmark/global_parallel/restart_ekp_par_calibration.sbatch
experiments/SCT4_benchmark/global_parallel/step_ekp.jl
experiments/SCT4_benchmark/global_parallel/step_ekp.sbatch
experiments/SCT4_benchmark/hpc_parallel/ekp_calibration.sbatch
experiments/SCT4_benchmark/hpc_parallel/init.jl
experiments/SCT4_benchmark/hpc_parallel/init.sbatch
experiments/SCT4_benchmark/hpc_parallel/precondition_prior.jl
experiments/SCT4_benchmark/hpc_parallel/precondition_prior.sbatch
experiments/SCT4_benchmark/hpc_parallel/restart.jl
experiments/SCT4_benchmark/hpc_parallel/restart.sbatch
experiments/SCT4_benchmark/hpc_parallel/restart_ekp_calibration.sbatch
experiments/SCT4_benchmark/hpc_parallel/single_scm_eval.jl
experiments/SCT4_benchmark/hpc_parallel/single_scm_eval.sbatch
experiments/SCT4_benchmark/hpc_parallel/step_ekp.jl
experiments/SCT4_benchmark/hpc_parallel/step_ekp.sbatch

Add SCT4 benchmark
