CliMA/CalibrateEDMF.jl

- src/helper_funcs.jl
This PR ensures that we can get the height vector from both LES (PyCLES) and TC.jl. It is also compatible with SCAMPy. The previous version had stopped working due to variable name changes in TC.jl, where `z_half` is now `zc` and `z` is now `zf`.
> Simplify height getter, ensure compatibility with PyCLES/TC.jl/SCAMPy.

- Project.toml
- experiments/les_strats/tc_calibrate.jl
- experiments/scm_pycles_pipeline/hpc_parallel/init.jl
- experiments/scm_pycles_pipeline/julia_parallel/calibrate.jl
- src/ReferenceModels.jl
- src/ReferenceStats.jl
- src/TurbulenceConvectionUtils.jl
- src/helper_funcs.jl
- test/ReferenceModels/runtests.jl
- test/runtests.jl
1) address comments from from #45: primarily reverting to using getter method for ReferenceModel dirs
2) automate specification of additional LES simulations
> Automate specification of additional LES simulations

- experiments/scm_pycles_pipeline/hpc_parallel/config.jl
- experiments/scm_pycles_pipeline/julia_parallel/calibrate.jl
- src/CalibrateEDMF.jl
- src/LESUtils.jl
- src/TurbulenceConvectionUtils.jl
- src/helper_funcs.jl
- test/LESUtils/runtests.jl
- test/TurbulenceConvectionUtils/runtests.jl
- test/runtests.jl
This PR creates the LESUtils module, which will house all LES-related utils. 
I have also moved the `generate_uuid` function to TurbulenceConvectionUtils and given it a more specific name. I have also added asserts in that function to make sure that the call is to a legal case, as specified by the `LES_library` dict.
> Create LESUtils module, reorganize src.

- experiments/les_strats/tc_calibrate.jl
- experiments/scm_pycles_pipeline/config.jl
- src/CalibrateEDMF.jl
- src/LESUtils.jl
- src/ModelTypes.jl
- src/Pipeline.jl
- src/ReferenceModels.jl
- src/ReferenceStats.jl
- src/TurbulenceConvectionUtils.jl
- src/helper_funcs.jl
- test/Pipeline/config.jl
- test/Pipeline/runtests.jl
- test/ReferenceModels/runtests.jl
> Mean covar paths

- src/NetCDFIO.jl
- src/Pipeline.jl
- src/TurbulenceConvectionUtils.jl
- test/NetCDFIO/runtests.jl
> Add conditional sampling for versions, save batch_size in diagnostics output.

- experiments/scm_pycles_pipeline/hpc_parallel/step_ekp.jl
- src/NetCDFIO.jl
- src/Pipeline.jl
- test/NetCDFIO/runtests.jl
This PR:
- Adds diagnostics for the parameter mean in unconstrained and constrained space.
- Enables batching using UKI.
> Add more ensemble diagnostics, enable UKI batching.

- src/Pipeline.jl
- src/ReferenceModels.jl
- test/Pipeline/runtests.jl
This PR:
- Extends the Pipeline tests to include a calibration process with batching enabled. It also extends the test to a calibration process using UKI.
- Increases the code coverage to 72.53%.
> Test minibatching pipeline.

- src/LESUtils.jl
This PR makes the LES_dictionary consistent with the current "working" cfSites, which correspond to those simulations in Shen et al that will not undergo revision in the coming months.
As more simulations are corrected and verified, we can expand upon these allowed sites.
> Only allow use of cfSites from Shen et al.

- src/DistributionUtils.jl
- test/DistributionUtils/runtests.jl
Add test for `flatten_param_dict`
> add test for flatten_param_dict

- src/ReferenceStats.jl
- src/TurbulenceConvectionUtils.jl
- test/ReferenceStats/runtests.jl
- test/TurbulenceConvectionUtils/runtests.jl
Ensure `adapt_dt` is set to TC default after running reference sim.
> ensure adapt_dt is set to TC default after running reference sim

- src/TurbulenceConvectionUtils.jl
- src/helper_funcs.jl
- test/TurbulenceConvectionUtils/runtests.jl
This PR should allow changing any nested dictionary through namelist_args. I added a few options to the tests to make sure of it.
> Allow modification of namelist_args for all kinds of nested dictionaries.

- ekp_experimental/failsafe_inversion.jl
- src/ReferenceStats.jl
- Generalizes typing for failsafe_inversion functions.
- Adds small variance inflation factor to sample covariance matrix from successful ensemble if original matrix is singular.
> Generalize typing, implement last-resort variance inflation in sample_succ_gaussian.

- src/Diagnostics.jl
- src/Pipeline.jl
- src/ReferenceStats.jl
- test/NetCDFIO/runtests.jl
- test/Pipeline/runtests.jl
- Adds mse_full diagnostics at the particle closest to the ensemble mean parameter.
- Adds failure diagnostics (number of particles that failed per iteration).
- Simplifies codebase.
> Add nearest neighbor diagnostics, simplify codebase.

- .buildkite/pipeline.yml
- bors.toml
- experiments/scm_pycles_pipeline/julia_parallel/calibrate.jl
This PR adds a buildkite pipeline that runs the julia parallel calibrate
> Add buildkite pipeline

- src/LESUtils.jl
- src/helper_funcs.jl
- test/LESUtils/runtests.jl
This should fix some of the existing memory leaks (some of the NC files are not closed).
> Use do syntax for Dataset

- src/helper_funcs.jl
This PR refactors some code and removes a try-catch statement.
> Refactor, remove try-catch

- src/DistributionUtils.jl
- src/HelperFuncs.jl
- src/LESUtils.jl
- src/Pipeline.jl
- src/ReferenceModels.jl
- src/ReferenceStats.jl
- src/TurbulenceConvectionUtils.jl
This PR improves some code loading, and trims some trailing spaces.
> Improve code loading

- .buildkite/pipeline.yml
This PR fixes a few things missed in #215.
> Fix slurm args

- integration_tests/julia_parallel_calibrate.jl
Hopefully this will help with reproducibility.
> Add random seed for integration test

- integration_tests/julia_parallel_calibrate.jl
This PR adds a subplot for the validation set.
> Add validation plot

- integration_tests/julia_parallel_calibrate.jl
I'm not sure if this is how we want to do this, but I think we can now increase the number of iterations.
> Increase n-iterations for integration test

- src/Diagnostics.jl
- src/HelperFuncs.jl
- src/LESUtils.jl
- src/ReferenceModels.jl
- src/ReferenceStats.jl
- src/TurbulenceConvectionUtils.jl
- src/parallel.jl
- test/LESUtils/runtests.jl
- test/ReferenceStats/runtests.jl
> Prep for removing get_stats_path

- .buildkite/pipeline.yml
- integration_tests/download_artifacts.jl
- src/LESUtils.jl
- src/artifact_funcs.jl
This PR makes the artifacts actually download lazily. See [this comment](https://github.com/CliMA/TurbulenceConvection.jl/pull/876#issue-1160517643).
> Lazily download artifacts

- src/TurbulenceConvectionUtils.jl
- test/TurbulenceConvectionUtils/runtests.jl
- tools/DiagnosticsTools.jl
- tools/README.md
- tools/TCRunner.jl
Add general set of tools for analyzing `CalibrateEDMF.jl` output and running `TurbulenceConvection.jl` with optimal parameters. Include more generic `SCM_handler`
> Add diagnostics tools

- .dev/up_deps.jl
- integration_tests/Manifest.toml
Also  update integration test manifest.
> Add convenience function to update dependencies

- .buildkite/pipeline.yml
- bors.toml
> Add buildkite unit tests back in

- docs/bibliography.bib
- integration_tests/Manifest.toml
- src/Diagnostics.jl
- src/HelperFuncs.jl
- src/LESUtils.jl
- src/Pipeline.jl
- src/ReferenceStats.jl
- src/TurbulenceConvectionUtils.jl
> Fixes to API literation, update bibliography

- Project.toml
- integration_tests/Manifest.toml
> Bump version.

- docs/src/API/Diagnostics.md
- src/Diagnostics.jl
Expands API documentation coverage for the diagnostics module.
> Expand diagnostics documentation

- docs/src/API/Diagnostics.md
- src/TurbulenceConvectionUtils.jl
Adds an introduction to the Diagnostics.jl module in the API documentation.
Improves API coverage of TurbulenceConvectionUtils.jl
> Add introduction to Diagnostics documentation

- docs/src/API/Diagnostics.md
- integration_tests/Manifest.toml
- src/Diagnostics.jl
- src/Pipeline.jl
- src/ReferenceModels.jl
- src/ReferenceStats.jl
- test/ReferenceModels/runtests.jl
Improve documentation of structs and constructors in ReferenceModels, ReferenceStatistics.
Add documentation of several diagnostics utility functions.
> Improve documentation of structs and constructors

- docs/make.jl
- docs/src/API/Pipeline.md
- docs/src/getting_started.md
- integration_tests/Manifest.toml
- src/TurbulenceConvectionUtils.jl
Adds a Getting started section to the docs, pointing to the experiment section.
#315
> Add Getting started section to docs.

- integration_tests/Manifest.toml
- src/Diagnostics.jl
- src/NetCDFIO.jl
- src/Pipeline.jl
- up_deps.sbatch
Adds validation loss diagnostics in latent space. These are diagnostics that track the error the EKP would see if it was trained on the validation loss (although of course it isn't), including the effect of L2 regularization.
> Add validation loss diagnostics.

- integration_tests/Manifest.toml
- src/LESUtils.jl
- src/ReferenceModels.jl
- test/LESUtils/runtests.jl
Add new LES runs for deep convection to available LES library.
> add deep convection cases to LES Library

- experiments/scm_pycles_pipeline/hpc_parallel/init.sbatch
- experiments/scm_pycles_pipeline/hpc_parallel/precondition_prior.sbatch
- experiments/scm_pycles_pipeline/hpc_parallel/single_scm_eval.sbatch
- experiments/scm_pycles_pipeline/hpc_parallel/step_ekp.sbatch
- integration_tests/Manifest.toml
- src/Pipeline.jl
> Fix order of validation diags, failsafe sysimage

- integration_tests/Manifest.toml
- tools/DiagnosticsTools.jl
- tools/README.md
- tools/TCRunner.jl
- tools/test_set_config.jl
Add capability to run optimal parameters on training (reference) set and a newly defined test set.
> Add training (reference) and test set capability to tools

- .buildkite/pipeline.yml
- integration_tests/Manifest.toml
- src/HelperFuncs.jl
- src/ReferenceModels.jl
- test/HelperFuncs/runtests.jl
- test/ReferenceModels/runtests.jl
- test/runtests.jl
LinRange -> range (thanks to @haakon-e for pointing our rounding errors in LinRange),
Add more coverage for HelperFuncs module
> Expand coverage for HelperFuncs, LinRange -> range.

- docs/make.jl
- docs/src/contributing.md
- integration_tests/Manifest.toml
> Add contributing guide.

- integration_tests/Manifest.toml
update `integration_tests` manifest.
> update integration_tests manifest

- Project.toml
- integration_tests/Manifest.toml
> Bump version

- .buildkite/pipeline.yml
Temporarily removes the Sparse Inversion integration test until brittleness issues are solved upstream in EnsembleKalmanProcesses.jl.
> Remove SparseInversion test until issues are solved upstream.

- README.md
- docs/make.jl
- docs/src/getting_started.md
- docs/src/installation.md
Adds an installation guide to the docs, and the Zenodo badge containing the DOI of the latest stable release of the package.
> Add installation guide and DOI badge.

- integration_tests/Manifest.toml
- tools/DiagnosticsTools.jl
Display information DiagnosticsTools functions for where optimal parameters are found.
> add info to DiagnosticsTools

- README.md
- integration_tests/Manifest.toml
> Resolve to latest DOI

- integration_tests/Manifest.toml
- src/HelperFuncs.jl
Fixes locations of PyCLES variables.
> Fix location of PyCLES variables.

- integration_tests/Manifest.toml
- tools/TCRunner.jl
- tools/TCRunner.sbatch
Extend TCRunner for ensemble runs
> feat: TCRunner ensemble

- docs/src/API/HelperFuncs.md
> docs: fix ParameterMap docs references

- integration_tests/Manifest.toml
- src/KalmanProcessUtils.jl
- src/Pipeline.jl
Enables the use of EnsembleKalmanProcess localizers.
#320
> Enable use of localizers

- Project.toml
- experiments/grid_search/quick_plots.jl
- integration_tests/Manifest.toml
- integration_tests/SCT1_integration_test_config.jl
> Release v0.5

- docs/make.jl
- docs/src/tc_runner.md
- integration_tests/Manifest.toml
> add TCRunner to docs

- integration_tests/Manifest.toml
- src/ReferenceStats.jl
- test/ReferenceStats/runtests.jl
> Add normalize kwarg to time_cov, test options

- Project.toml
- integration_tests/Manifest.toml
Release v0.6 of CalibrateEDMF.
> Release v0.6

- src/LESUtils.jl
- test/LESUtils/runtests.jl
Adds a shallow LES dictionary.
> Add shallow LES dict

- Project.toml
- experiments/scm_pycles_pipeline/hpc_parallel/sysimage.sbatch
> Release v0.7, last before update to TC >= 0.34.

- README.md
- docs/src/index.md
- integration_tests/Manifest.toml
- up_deps.sbatch
> Update reference to paper.

- experiments/SCT1_benchmark/NN_closure/buoy_vel_no_reg/e100/config.jl
- experiments/SCT1_benchmark/NN_closure/buoy_vel_no_reg/e50/config.jl
- experiments/SCT1_benchmark/NN_closure/buoy_vel_reg_0.1/config.jl
- experiments/SCT1_benchmark/NN_closure/inv_z_l2_reg_0.1/config.jl
- experiments/SCT1_benchmark/NN_closure/inv_z_no_reg/e100/config.jl
- experiments/SCT1_benchmark/NN_closure/inv_z_no_reg/e50/config.jl
- experiments/SCT1_benchmark/NN_closure/none_no_reg/e100/config.jl
- experiments/SCT1_benchmark/NN_closure/none_no_reg/e50/config.jl
- experiments/SCT1_benchmark/NN_closure/none_reg_0.1/config.jl
- experiments/SCT2_benchmark/NN_closure/inv_z_no_NN_reg/config.jl
- experiments/SCT2_benchmark/config.jl
- experiments/SCT3_benchmark/config_no_phys.jl
- integration_tests/Manifest.toml
Update specification entrainment closure in benchmark configs to account for changes in `TC v1.2`
> update entr specification in configs for TCv1.2

- src/HelperFuncs.jl
- test/HelperFuncs/runtests.jl
- test/runtests.jl
Adds allocation tracker for unit tests.
Tracking #471 .
> Track unit test allocations.

- integration_tests/Manifest.toml
> Up tc deps

- src/DistributionUtils.jl
- test/DistributionUtils/runtests.jl
Allow functionality for unique prior `σ`s to be specified seperately for each parameter in the config file as a dictionary (consistent with mean and constraint dictionaries). Previously, only a single `σ` could be specified for all parameters.
> Allow variable prior sigma

- .buildkite/pipeline.yml
- Project.toml
Update buildkite CI workflows to use new-central nodes
> Update to new-central

- src/Pipeline.jl
- src/ReferenceStats.jl
Add optional scaling factor for pooled variance calculation, used to compute the observation noise cov matrix.
> Add observation noise covariance scaling factor

- .buildkite/pipeline.yml
- CES/Project.toml
- CES/linreg_ces.jl
- Project.toml
- integration_tests/Het_batch_unscented_test_config.jl
- integration_tests/Manifest.toml
Add CES script for linear regression.
> Add CES script for linear regression
